### ISSUE TITLE
support for `python` as `python3`

### ISSUE THREAD

**Issue by sbinet** [alisw/alibuild#276] opened 2016-05-19 15:36 UTC
Many Linux distributions made the switch to `python3`.

`aliBuild` and friends should explicitly request `python2` instead of `python` to cater for the future (or migrate to `python3` but that's understandably more work.)

**Comment by ktf** [comment] 2016-05-19 15:56
Duplicate of #205. It's actually not so much work, probably.

**Closed by ktf** 2016-05-19 15:56 UTC
