### ISSUE TITLE
Feature request: Support for defaults in aliDeps

### ISSUE THREAD

**Issue by PMunkes** [alisw/alibuild#463] opened 2017-07-26 06:27 UTC
Currently aliDeps uses only the dependencies in the base recipe and does not recognize any defaults passed to it. As defaults can, and do, change the dependencies of many packages, it would be an improvement to have this updated dependency graph.
An example of a package affected by this would be FairRoot with the default o2-dev-fairroot.

**Comment by ktf** [comment] 2017-07-26 08:29
Agreed.

**Comment by ktf** [comment] 2018-01-19 12:48
Closing this as duplicate of #512 since there @Barthelemy uses the new naming.

**Closed by ktf** 2018-01-19 12:48 UTC
