### ISSUE TITLE
Python changes in Homebrew

### ISSUE THREAD

**Issue by syamasak** [alisw/alibuild#499] opened 2017-11-13 10:26 UTC
Homebrew's python package stopped shadowing system python,
https://github.com/Homebrew/homebrew-core/pull/14408
Due to this change, globally installed (by brew) python packages will not be picked. (prefer_system_check condition does not satisfy because system python cannot find pip packages)

```
$ which python
/usr/bin/python
$ which python2
/usr/local/bin/python2
$ which python3
/usr/local/bin/python3
$ python -V
Python 2.7.10
$ python2 -V
Python 2.7.14
$ python3 -V
Python 3.6.3
$ pip -V
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
$ pip2 -V
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
$ pip3 -V
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
```
(Clean installed High Sierra + brew install python python3)

**Comment by dberzano** [comment] 2017-11-15 22:26
Hi @syamasak, Homebrew's behaviour is finally correct. Nothing should ever shadow any system default package (you fix this, but you break a thousand of that, if you know what I mean).

So, instead of getting Python+pip with Homebrew, just install plain pip on top of your system Python installation, and use that pip to install packages:

    sudo easy_install pip
    sudo pip install blah blah blah

Can you please try and report? Also: aliBuild works fine, this is an installation issue related to the recipes (alidist).

**Comment by syamasak** [comment] 2017-11-20 11:03
Hi @dberzano, for some reason easy_install didn't work, but the following worked for me:
```
sudo rm `which pip` # remove Homebrew's pip symlink in advance
curl -O https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
for X in "mock==1.0.0"         \
         "numpy==1.9.2"        \
         "certifi==2015.9.6.2" \
         "ipython==5.1.0"      \
         "ipywidgets==5.2.2"   \
         "ipykernel==4.5.0"    \
         "notebook==4.2.3"     \
         "metakernel==0.14.0"  \
         "pyyaml"
do
  pip install --user $X
done
cd ~/alice
python3 alibuild/aliBuild --defaults root6 build ROOT --debug
```
I thought it's better for the recipes to use Homebrew's python{2,3} OR to suggest users to install plain pip and the packages with it.

**Comment by dberzano** [comment] 2017-11-20 11:08
Yes this solution:

```
curl -O https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
```

is indeed more generic, thanks for pointing it out.

I don't however understand why you prepend `python3` to aliBuild - aliBuild works both with Python 2 and Python3, you normally don't have to care at all, but if this works for you, then fine.

Closing as the problem is solved! :-)

**Closed by dberzano** 2017-11-20 11:08 UTC
