### ISSUE TITLE
Rename log file from 'log' to 'log.txt' 

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alibuild#447] opened 2017-05-09 07:53 UTC
Github refuses to upload a file called 'log'. So each time I have to rename it to log.txt.

**Comment by ktf** [comment] 2017-05-09 08:12
Duplicate of #406 . Closing.

**Closed by ktf** 2017-05-09 08:12 UTC

**Comment by Barthelemy** [comment] 2017-05-09 09:09
Lol, I have memory problems...

**Comment by ktf** [comment] 2017-05-09 11:13
And I've a long todo list... ;-)
