### ISSUE TITLE
Wrong gcc version loaded

### ISSUE THREAD

**Issue by rqwa** [alisw/alibuild#208] opened 2016-04-19 14:12 UTC
I tried to install aliphysics and aliroot on SL 6.6 with the following components:
Python 2.7.8
cmake version 2.8.12.1
gcc 4.8.4

The components are loaded with `module load ...`

For the installation process I used the following commands:
`aliBuild init AliRoot,AliPhysics -z ali-master`
`aliDoctor 2>&1 | tee -a alidoctor.log`
`aliBuild -z -w ../sw build AliPhysics --jobs 10 --disable fastjet 2>&1 | tee -a build.log`

The installation process fails when installing XRootD, because the used compiler is gcc 4.4.7 and not 4.8.4 anymore.
The log files and the output of aliDoctor are attached. 
The same problem appears when using gcc 5.2.0 and disabling the GCC-toolchain

[log.txt](https://github.com/alisw/alibuild/files/226044/log.txt)
[alidoctor.txt](https://github.com/alisw/alibuild/files/226047/alidoctor.txt)
[build.txt](https://github.com/alisw/alibuild/files/226048/build.txt)

**Comment by ktf** [comment] 2016-04-19 15:04
How do you install your system? Is it using devtools? Can you provide a recipe to bring your system from a vanilla 6.6 to your setup?

**Comment by rqwa** [comment] 2016-04-19 17:00
Sorry I cannot provide a recipe how get vanilla 6.6 to the current setup, as the computer is a cluster which I only use as user.
I have two additional remarks:
- gcc 4.4.7 is the default compiler loaded without specifying any gcc version or after unloading gcc, if the script performs a `module unload gcc` this could be the cause of the error
- I installed alibuild with `pip install --user alibuild` as I only have limited rights

**Comment by rqwa** [comment] 2016-05-03 10:51
After some more test I managed to install alibuild successfully via alibuild.
First I installed alibuild via `pip install --user alibuild`, for this I needed to load python 2.7.8 via environment-modules, as pip is no included in python 2.6.6.
Then I unloaded all python and gcc versions from the environment-modules and started alibuild with the default gcc and python version.
If I include any python module the build crashes, as described in #209, if I include any gcc module I get the described in this ticket.

**Comment by dberzano** [comment] 2016-06-14 10:26
Hello all, we've found an interesting thing. What happens when you do:

```
which cc
which c++
ls -l $(which cc) $(which c++)
```

with your custom GCC modulefile loaded?

It seems that XRootD looks for `cc` and `c++`, and vanilla GCC installations (i.e. not coming from a distribution's package) lack the former.

**Comment by jusaviin** [comment] 2016-06-14 10:35
The output of those command is:

jusaviin@electra:~$ which cc
/usr/bin/cc
jusaviin@electra:~$ which c++
/cvmfs/fgi.csc.fi/compilers/sl6/gnu/gcc/4.9.2/bin/c++
jusaviin@electra:~$ ls -l $(which cc) $(which c++)
-rwxr-xr-x 4 cvmfs cvmfs 3178907 Jul 10  2015 /cvmfs/fgi.csc.fi/compilers/sl6/gnu/gcc/4.9.2/bin/c++
lrwxrwxrwx 1 root  root        3 Aug 24  2015 /usr/bin/cc -> gcc

**Comment by rqwa** [comment] 2016-06-14 10:40
Hi @dberzano,
the output is the following.
```
[marquard@login01 ~]$ which cc
/usr/bin/cc
[marquard@login01 ~]$ which c++
/cm/shared/apps/gcc/4.8.4/bin/c++
[marquard@login01 ~]$ ls -l $(which cc) $(which c++)
-rwxr-xr-x 4 root root 3116106 Jan 31  2015 /cm/shared/apps/gcc/4.8.4/bin/c++
lrwxrwxrwx 1 root root       3 Jan 28  2015 /usr/bin/cc -> gcc
```

XRootD is not the only package with the problem. I also spotted Geant4_VMC have the same problem, but don't require c++11 and thus not break. I'm just running a new test to provide the logs.

**Comment by dberzano** [comment] 2016-06-14 10:49
Yes, the problem is occurring with every package using CMake because your GCC module is "broken".

What CMake does is finding a consistent pair of `cc` and `c++`: since your custom GCC does not provide `cc` (but `c++` only), it falls back on what is found under `/usr/bin` and subsequently fails.

We've updated the GCC-Toolchain check in order to force compilation of our own GCC in case `cc` is not found.

If you want to avoid using our own GCC-Toolchain (I guess that was your original idea in the end), you can:

* Ask your admins to update your module in order to include `cc` too (see our recipe to see how we do that; this is a standard in every Linux distributoin)
* Or, have in your `$PATH` a symlink to the correct `cc` to "monkey patch" the modulefile provided by your installation

Does this help?

**Comment by rqwa** [comment] 2016-06-14 10:55
Thanks for the explanation. I will talk to our admins.

**Comment by ktf** [comment] 2016-06-14 11:55
Closing this in favour of alisw/alidist#436.

**Closed by ktf** 2016-06-14 11:55 UTC
